### ISSUE TITLE
Could not connect to Twilio: Invalid Access Token signature

### ISSUE THREAD

**Issue by desaivishal11** [twilio/video-quickstart-js#11]
I am getting below error when connecting to room.

Could not connect to Twilio: Invalid Access Token signature

Running this under npm start and using URL: http://localhost:3000/quickstart/

**Comment by markandrus** [comment]
@desaivishal11 Are your environment variables set correctly? Either in `.env` or via the following environment variables (commands differ slightly on Windows):

```
export ACCOUNT_SID=xxx
export TWILIO_API_KEY=yyy
export TWILIO_API_SECRET=zzz
```

You should be able to check the generated Access Token by pasting the string into a tool like https://jwt.io and also pasting the signature into the "Validate Signature" portion:

1. Paste Access Token. It will initially show "Invalid Signature".

![screen shot 2017-05-17 at 12 53 16 pm](https://cloud.githubusercontent.com/assets/359154/26173204/da7122b4-3aff-11e7-9fa1-c079638d65c0.png)

2. Enter your API Key Secret. It should show "Signature Verified". Make sure not to leak it with anyone! I redacted mine in the screenshot below.

![image](https://cloud.githubusercontent.com/assets/359154/26173255/08b94624-3b00-11e7-8ce5-33058d68b184.png)

**Comment by desaivishal11** [comment]
I added environment variable correctly that's why I could start server at port 3000. I am able to click on join room.

**Comment by desaivishal11** [comment]
I couldn't use export cmd anyway.

**Comment by desaivishal11** [comment]
I used this too which you mentioned above. I used token generated from Twilio website. I put my secrete as well. Still says Invalid.

**Comment by desaivishal11** [comment]
Finally, I got token and I used it to validate. Signature is fine. Still getting error. 

2017-05-17 20:26:28.638Z | INFO in [connect #1]: Error while connecting to a Room: TwilioError {code: 20107, stack: "TwilioError: Invalid Access Token signature↵    at…ttp://localhost:3000/quickstart/index.js:4091:22)", message: "Invalid Access Token signature", name: "TwilioError"}

**Comment by markandrus** [comment]
Can you verify that you set `TWILIO_API_KEY` to the API Key SID? It is a 34-character string. The first two characters should be "SK" and the remaining 32 characters should be hexadecimal. The `TWILIO_API_SECRET` should be the API Key Secret shown once in the Twilio Console, which is a random string. I'm asking because it's easy to mix them up—in fact, I had a similar mixup just earlier today.

**Comment by desaivishal11** [comment]
Webpage is generating access token fine. I could see it in log. I verified using above tool you mentioned. Still getting this error to Token Signature.

**Comment by markandrus** [comment]
@desaivishal11 can you please verify

* That you set distinct values for `TWILIO_API_KEY` and `TWILIO_API_SECRET` and that `TWILIO_API_KEY` is a 34-character string beginning with "SK"? Like I said earlier, it's easy to mixup—I did it this morning—and ruling this issue out will help me troubleshoot your issue.
* That you set `TWILIO_API_SECRET` to your API Key's secret and _not_ your Auth Token?

It could be that tools like https://jwt.io are verifying your token because, from a JWT perspective, it is signed correctly; however, from Twilio's perspective, it may be signed with the wrong string. Additionally, a copy of an Access Token you are generating would be useful. Would you mind sharing it here? Alternatively, you can reach me at mroberts@twilio.com.

**Comment by desaivishal11** [comment]
Let me send info to your direct email. We can post outcome here for other people to see.

**Comment by markandrus** [comment]
@desaivishal11 and I have solved this issue over email by creating a new API Key to be used when signing Access Tokens.

**Comment by XemaA** [comment]
hi I have the same problem ! When I test with https://jwt.io/ I get a valid signature but in the app I still get the error "Could not connect to Twilio: Invalid Access Token signature". Could you please explain how I can fix this. Thanks :)

**Comment by Tanktiger** [comment]
@markandrus I have the same problemand tested different api keys but got this error every time. What else needed to be checked?

**Comment by Nik20112** [comment]
@markandrus Hi Can you please help me to solve it? because I have the same problem.

**Comment by rochapablo** [comment]
+1

anyone?

**Comment by arorashilpa** [comment]
+1 

Same issue. 
I get this error message everytime. 
**EMS service could not authenticate/authorize ether provided customer fpa token or twilio rtd token, unable to set FPA token**

Can anybody help me to resolve this??

**Comment by Batiskaf** [comment]
> and this error also- Provided grant token is not authentic or has expired
Having this error too by using react-native-twilio-chat, but only on iOS platform

**Comment by markandrus** [comment]
Hi y'all,

Please check with support@twilio.com. It is possible to construct an Access Token and sign the resulting JWT with _a secret_ such that the JWT validates when checked against the original secret. But that doesn't mean the secret—which must be the API Key Secret—is correct, and that the API Key SID used to construct the Access Token is correct. If either of these is untrue, or the Account SID is incorrect, etc., Twilio will reject it. Also, IIUC, you cannot use a trial account/test credentials when constructing the Access Token. Again, please write to support@twilio.com for more help here.

Thanks,
Mark

**Comment by shashwatsri1mg** [comment]
Token created from twilio console is working but one generated via twilio-ruby gem giving error - Invalid Access Token signature.
both the tokens have same output on https://jwt.io/ except one extra param i.e "nbf": 1585682883 in my token. Any help??

**Comment by amorimlucas** [comment]
Same issue here with twilio-ruby.

**Comment by superpromiser72** [comment]
POST https://ecs.us1.twilio.com/v2/Configuration 403

**Comment by superpromiser72** [comment]
app.js:5168 Unable to connect to Room: Access Token expired or expiration date invalid

please help me

**Comment by madmacc** [comment]
I am getting a similar issue when trying to join a room. I get the message "Invalid Access Token".
I have tried creating two API Keys (one standard and one master) but neither worked.   

Created as mentioned here: https://github.com/twilio/video-quickstart-js/tree/master#setup-requirements

We don't have to create the user or room beforehand do we?

**Comment by frontdevguy** [comment]
I had the same problem as I always got `Invalid Access Token`. The fix was to create a new API Key and make sure it's of type standard and not master

**Comment by yassernascimento** [comment]
"you cannot use a trial account/test credentials when constructing the Access Token";
If that info is true, I think this should be documented.

**Comment by hazem-taha** [comment]
I'm still having the same issue, any hope ??!!

**Comment by mariafernanda0821** [comment]
I generate the api key, but I don't know how to generate the secret of the api key, can you help me please

**Comment by sokhout-sao** [comment]
Hello, may be it could help those who has this issue.

I have found that the default region used in the exemple code was "US1" and that I have create my API KEY in the region "IE1".
Creating and using an API KEY made in the US1 region has resolve my problem and has made the exemple code work.

Now because I am in Europe region, i will try to figure how to set the default region as "IE1" in the SDK.
