### ISSUE TITLE
Does this not work with Android Webview

### ISSUE THREAD

**Issue by mnive93** [twilio/video-quickstart-js#141]
Wanted to confirm if Twilio does not work with Android webview. WebRTC streams within webview. Twilio does not support webview? Please help!

**Comment by manjeshbhargav** [comment]
Hi @mnive93 ,

twilio-video.js supports the following [browsers and platforms](https://www.twilio.com/docs/video/javascript#supported-browsers). By "support" we mean that we test extensively on the above mentioned platforms. There are a lot of other WebRTC enabled browsers (like Android WebView) that you are perfectly fine to use the SDK in, but since we don't test on them, you would be using it at your own risk. Hope this clears things up for you.

Thanks,

Manjesh Malavalli
JSDK Team

**Comment by Balasnest** [comment]
@mnive93 Did you manage to get it to work on the webview? Let us know your thoughts.

**Comment by piyush-mahapatra-au6** [comment]
Can i have updates of this thread? I am unable to make it work in web view

**Comment by ankit010cse80** [comment]
any updates to this ? has anyone able to make webview work  ?

**Comment by naderahmed** [comment]
yes. I have been having problems getting video to work in an Android webview, I think it is because the video only asks for audio permissions. However, when I play other non-twillio videos in the webview, those videos explicitly asks for video permissions and therefore works. This has caused a production outage, Can anyone provide guidance on this for us ASAP?

**Comment by ThomasCarltonInPerson** [comment]
+1
any news on this please ?

**Comment by IbrahimDrReddys** [comment]
> yes. I have been having problems getting video to work in an Android webview, I think it is because the video only asks for audio permissions. However, when I play other non-twillio videos in the webview, those videos explicitly asks for video permissions and therefore works. This has caused a production outage, Can anyone provide guidance on this for us ASAP?

Hi @naderahmed did you solve this issue??
