### ISSUE TITLE
How to Record Video using current Twilio Video Quickstart conference example? 

### ISSUE THREAD

**Issue by irshadhub** [twilio/video-quickstart-js#143]
I am using this example to handle Group Chat of participants. But I have not found any recording example in this project.

I have a few queries on video recording :

1. How can I start the recording of any participant's video with audio?
2. Is there any way to record the screen share?
3. How to record all running conference video? [ which is showing on my screen. ]

Please provide some working Examples.

**Comment by manjeshbhargav** [comment]
@irshadhub ,

Please refer to this [guide](https://www.twilio.com/docs/video/tutorials/understanding-video-recordings-and-compositions) in order to enable Room recordings. I will close this issue, but we can continue our discussion here if you need more clarification.

Thanks,

Manjesh Malavalli
JSDK Team
