### ISSUE TITLE
JS Video SDK latest version

### ISSUE THREAD

**Issue by nasreekar** [twilio/video-quickstart-js#20]
Which is the latest javascript SDK CDN that need's to be included in the html file?

The web app works fine when I use `<script src="//media.twiliocdn.com/sdk/js/video/releases/1.0.0-beta2/twilio-video.js"></script>` but then when I use the latest sdk CDN that is available on the site the web app doesn't work anymore. 
`<script src="//media.twiliocdn.com/sdk/js/video/v1/twilio-video.min.js"></script>`

And also using the old sdk, it doesnt support IOS . 

Can someone help me with this?

**Comment by markandrus** [comment]
Hi @nasreekar,

As of writing, the latest version is 1.2.2. If you develop a project using Node/NPM, you can just add it to your dependencies using

```
npm install --save twilio-video
```

Otherwise, you can use the following CDN links:

* https://media.twiliocdn.com/sdk/js/video/releases/1.2.2/twilio-video.js
* https://media.twiliocdn.com/sdk/js/video/releases/1.2.2/twilio-video.min.js
* https://media.twiliocdn.com/sdk/js/video/releases/1.2.2/docs

As far as your web app working fine when using 1.0.0-beta2 versus the v1 URL you shared, that v1 URL should redirect to the 1.2.2 URL above. There were breaking API changes between the 1.0.0-beta2, -beta3, etc., releases and 1.0.0. Your web app probably needs to be update to use these new APIs.

Does that make sense?

Best,
Mark
