### ISSUE TITLE
Simplified version?

### ISSUE THREAD

**Issue by tigerfarm** [twilio/video-quickstart-js#36]
I am successful to run the sample, thank you. However, I want to port it to PHP, but I don't know what is the minimum files I need to port. The "npm start" command seems to do a lot steps. The node_modules directory is huge. Are these just the Node runtime files, or are they part of the Twilio Video SDK? 

I'm looking for a minimum, easy to start sample, that's easy to follow and read. Let me know if you have such a sample. Note, I can generate access tokens using my Twilio Function (https://www.youtube.com/watch?v=5lrdYBLEk60).

**Comment by markandrus** [comment]
Hi @tigerfarm,

`node_modules` contains all the libraries used by the Node-based application server. Node's default package manager, `npm`, will auto-populate this directory with the application server's dependencies (and transitive dependencies) as specified in [`package.json`](https://github.com/twilio/video-quickstart-js/blob/65043a26790fd77f829a365d491eb44cc449aed4/package.json#L44) whenever `npm install` is run.

The most important dependencies for the application server are [express](http://expressjs.com) (an HTTP server) and the Node [twilio](https://www.npmjs.com/package/twilio) helper library (for interacting with Twilio's REST API, or generating Access Tokens). express serves not only the client-side application (i.e., [`index.html`](https://github.com/twilio/video-quickstart-js/blob/65043a26790fd77f829a365d491eb44cc449aed4/quickstart/public/index.html), [`index.css`](https://github.com/twilio/video-quickstart-js/blob/65043a26790fd77f829a365d491eb44cc449aed4/quickstart/public/index.css), and [`index.js`](https://github.com/twilio/video-quickstart-js/blob/65043a26790fd77f829a365d491eb44cc449aed4/quickstart/src/index.js)), it also provides the [`/token` endpoint](https://github.com/twilio/video-quickstart-js/blob/65043a26790fd77f829a365d491eb44cc449aed4/server/index.js#L54) for generating Access Tokens. Although `node_modules` also contains `twilio-video.js`, this dependency can instead be loaded from, e.g.

    https://media.twiliocdn.com/sdk/js/video/releases/1.6.1/twilio-video.min.js

If you re-implement the application server in PHP, you will not have these dependencies. You'll just need

* An Access Token endpoint (e.g., the Twilio Function you described) to replace `/token`—make sure to secure this.
* A way to serve `index.html` *
* A way to serve `index.css`
* A way to serve `index.js` **

\* `index.html` should have a &lt;script&gt; tag that points to the `twilio-video.min.js` URL above.
** `index.js` will need to be updated to refer to `Twilio.Video` instead of `Video` (and the [`var Video = require('twilio-video');`](https://github.com/twilio/video-quickstart-js/blob/65043a26790fd77f829a365d491eb44cc449aed4/quickstart/src/index.js#L3) line should be deleted. This is because the &lt;script&gt; tag will be used to load `twilio-video.js` instead of `require`.

***

We do have a minimal [Usage Example](https://github.com/twilio/twilio-video.js#usage) in the `README.md` of https://github.com/twilio/twilio-video.js. It doesn't include any of the CSS or other assets in this project. But if you want a bare-bones example, it will work.

Does this help?
Mark

**Comment by tigerfarm** [comment]
A colleague sent me the following link which is a the simple straight forward sample I was looking for: https://github.com/kedartoraskar/video-quickstart-php.
I had it working within minutes.
Thanks for the above documentation.

**Comment by markandrus** [comment]
Thanks @tigerfarm!
