### ISSUE TITLE
Enable disable video audio

### ISSUE THREAD

**Issue by cipriancaba** [twilio/video-quickstart-js#41]
It's not really clear from the examples or documentation what is the way to enable or disable a local track (audio or video)

Also, it's not clear to me what `track.attach()` is doing and if should be called for both video and audio tracks..

Thanks for clarifying

**Comment by markandrus** [comment]
Hi, @cipriancaba,

> It's not really clear from the examples or documentation what is the way to enable or disable a local track (audio or video)

Sorry it's not clear. To enable or disable a LocalAudioTrack or LocalVideoTrack, you can do the following:

```js
localTrack.enable();
localTrack.disable();
```

There's some more information on this in the API docs for [LocalAudioTrack](http://media.twiliocdn.com/sdk/js/video/releases/1.8.0/docs/LocalAudioTrack.html) and [LocalVideoTrack](http://media.twiliocdn.com/sdk/js/video/releases/1.8.0/docs/LocalVideoTrack.html).

> Also, it's not clear to me what track.attach() is doing and if should be called for both video and audio tracks..

`attach` is a method on [AudioTrack](http://media.twiliocdn.com/sdk/js/video/releases/1.8.0/docs/AudioTrack.html) and [VideoTrack](http://media.twiliocdn.com/sdk/js/video/releases/1.8.0/docs/VideoTrack.html). It creates or updates an HTMLMediaElement and sets its `srcObject` attribute to a MediaStream containing an AudioTrack or VideoTrack's underlying MediaStreamTrack. This enables audio or video playback in the browser. If you have an AudioTrack and VideoTrack from the same Participant, you should attach them to the same HTMLMediaElement. If a Participant has more than one VideoTrack, you'll want to attach to the additional VideoTrack(s)—like a screenshare VideoTrack—to separate HTMLMediaElements, since browsers don't have great support for multi-track `<video />` elements yet.

That's a mouthful, but hopefully that clarifies?

* `attach` tracks to new or existing HTMLMediaElements in the DOM (`<audio />` or `<video />`)
* `attach` audio and video tracks from the same Participant in the same `<video />`

Let me know if I can help in any other way,
Mark

**Comment by cipriancaba** [comment]
Wow @markandrus, that's a pretty awesome quick response... thanks so much for clarifying.. maybe we can add this somewhere in the docs?

Thank you

**Comment by mikron123** [comment]
Why are the docs still lacking this fundamental information? seriously, you're selling a product and cannot make a simplified walk through of how to achieve  basic mute/unmuate functionality?
Why is it not part of your basic demo that you provide?

We're on the verge of deciding if to use it, and these are the type of things that make us think twice.

**Comment by makarandp0** [comment]
Hello @mikron123, This is really old thread - that refers to 1.x api. I suspect you are using 2.x API - and we do have some [sample code](https://github.com/twilio/video-quickstart-js/tree/master/examples/localmediacontrols) that demonstrates the usage of mute unmute functionality. Please let me know  if that helps.

Thanks,
Makarand

**Comment by VincentSim** [comment]
Hi @makarandp0,

In your code you don't show how to mute/unmute localParticipant.
I think it deals with publication subscribed or not but I didn't find an example. 
Could you please give one example ?

Thanks

**Comment by makarandp0** [comment]
@VincentSim - Please check out: https://github.com/twilio/video-quickstart-js/blob/master/examples/localmediacontrols/src/helpers.js#L9

Let me know if it does not work. However one problem with muting video this way is your camera would still stay on, to turn off camera completely you would need to  unpublish/stop the local track - @timmydoza explained this here: https://github.com/twilio/twilio-video-app-react/issues/180

Thanks,
Makarand
