### ISSUE TITLE
Participant Track freezes instead of going black/blank when it is disabled.

### ISSUE THREAD

**Issue by sonalikatara** [twilio/video-quickstart-js#63]
When a participant pauses a video track   ` track.disable();`, the container element turns blank most of the times but sometimes it shows a frozen track. 

How do I get rid of the frozen track?

**Comment by manjeshbhargav** [comment]
Hi @sonalikatara ,

Thanks for writing in with your issue. I have a few questions:

1. Does this happen only on some browsers or all browsers?
2. Are you using a peer-to-peer or group Room?

Thanks,

Manjesh Malavalli
JSDK Team

**Comment by sonalikatara** [comment]
Hi @manjeshbhargav,

1. It happens in chrome and safari browsers in Windows devices, MacBooks, iPhones, and Android devices.
2. It's a small-group room with the video-codec set to H.264.

Please let me know if you need any other information from me.

Thank You,
Sonali

**Comment by manjeshbhargav** [comment]
Hi @sonalikatara ,

Sorry for the delayed response. In a group or small group Room, the media server stops forwarding frames to the RemoteParticipant when the LocalTrack is disabled. So, it is natural that sometimes you can see frozen video because of it.

I recommend that you overlay the <video> element on top of an <img> so that, when you get the "disabled" event on the RemoteTrack, you hide the corresponding <video> element so that the user can see the <img> in its place. Once a RemoteTrack receives the "enabled" event, you can then show the <video> element again.

Please let me know if this helps.

Thanks,

Manjesh Malavalli
JSDK Team

**Comment by sonalikatara** [comment]
Thank You @manjeshbhargav,
That explains why the tracks go blank or freeze at times. Yes I can overlay the track element on top of an element and then hide/show this element when the track is enabled/disabled.

**Comment by manjeshbhargav** [comment]
Hi @sonalikatara ,

Good to know that you're unblocked. I will close this issue.

Thanks,

Manjesh Malavalli
JSDK Team
