### ISSUE TITLE
Video Recording API

### ISSUE THREAD

**Issue by jinman** [twilio/video-quickstart-js#66]
Is there any sample that shows how to use room recording API to just show the recordings in a chronological order after the call was made?

**Comment by manjeshbhargav** [comment]
Hi @jinman ,

You can configure a Room to be recorded while creating it using the [REST API](https://www.twilio.com/docs/video/api/rooms-resource#post-parameters) by using the `recordParticipantsOnConnect` parameter. You can then access the recordings using our [Recordings](https://www.twilio.com/docs/video/api/recordings-resource) and [Compositions](https://www.twilio.com/docs/video/api/compositions-resource) APIs. The Video SDK does not interact with our recording infrastructure.

I hope I've clarified things for you. I will close this issue since I have answered your question. Please feel free to comment here if you have further questions about recordings.

Thanks,

Manjesh Malavalli
JSDK Team
