### ISSUE TITLE
is there a way to limit peer to peer only 2?

### ISSUE THREAD

**Issue by nmssalman** [twilio/video-quickstart-js#70]
i want to limit number of users per call only 2, is there a way?

**Comment by manjeshbhargav** [comment]
Hi @nmssalman ,

You can specify the maximum number of Participants in a Room (`maxParticipants`) while creating a Room using the [Twilio Video REST API](https://www.twilio.com/docs/video/api/rooms-resource#post-parameters).

I will close the issue since I have answered your question. Please let me know if this works for you.

Thanks,

Manjesh Malavalli
JSDK Team

**Comment by nmssalman** [comment]
im using the following project as my template, can you suggest me the exact place to put the limitations of participants?

https://github.com/twilio/video-quickstart-js
