### ISSUE TITLE
Very bad echo in mobile web

### ISSUE THREAD

**Issue by rahul1346** [twilio/video-quickstart-js#78]
Got it to work and run on my mobile safari browser and chrome web browser. While the video quality is great, the feedback echo caused by the speaker/microphone in the iPhone (could be other devices) causes a very bad and elongated echo.

Is anyone else experiencing this and is there solution?

**Comment by manjeshbhargav** [comment]
@rahul1346 ,

Thanks for writing in with your question. Were the mobile and desktop clients close by? That might explain why you are hearing the echo. The underlying browser technology that we use for media (WebRTC) usually takes care of echo cancellation.

Thanks,

Manjesh Malavalli
JSDK Team

**Comment by rahul1346** [comment]
Thanks @manjeshbhargav . They were in close proximity however the speaker volume on the laptop was turned off.

**Comment by manjeshbhargav** [comment]
Hi @rahul1346 ,

Yes, but I think since the microphone is active, there is an audio feedback loop which will result in the echo, even though the speaker volume is off. Please try running your app with the two devices apart.
I think that will get rid of the echo.

Thanks,

Manjesh Malavalli
JSDK Team
